### ISSUE TITLE
How to export DNG images from MLV using MLV.APP in batch?

### ISSUE THREAD

**Issue by hcwang95** [proteus1991/RawVSR#1]
Thanks for providing the original raw video and detailed code base!

I am wondering how do you extract DNG image sequences from MLP.APP automatically? What I could found is only exporting the current frame, which is hard to process all videos manually.

Thanks for your help in advance!

**Comment by proteus1991** [comment]
Hi, 

I remember that MLP.App supports exporting all video frames in DNG format with one click. You can try File -> Export Selected Clips. Let me know if you have any further problems.

Thanks,

Xiaohong

**Comment by hcwang95** [comment]
Thanks @proteus1991 , I've tried to export selected clips but the only option for me is to convert the MLV to 'mov' video. Is there anything I am doing wrongly?

**Comment by proteus1991** [comment]
Check Files -> Export settings -> Codec. You should find the **CinemaDNG uncompressed** option. Choose it to export video frames in DNG format.

**Comment by hcwang95** [comment]
That works, thanks a lot!
