### ISSUE TITLE
Unable to fetch training data

### ISSUE THREAD

**Issue by ShihMengLi** [proteus1991/RawVSR#2]
Hi, @proteus1991 

Thanks for your amazing work. 
I am unable to fetch the RawVD dataset on BaiduYun. (It reports the link is out of date or incorrect.) 
Is there any work around method to get the the data (e.g. fetch the data from google drive) ?

**Comment by proteus1991** [comment]
Hi @ShihMengLi,

We have checked the link which is accessible. We cannot upload the whole data to google drive due to the space limitation.

Xiaohong

**Comment by ShihMengLi** [comment]
Hi, @proteus1991

Oh, I see. I figured out the problem comes from my internet domain. Thanks!
