### ISSUE TITLE
Question about data generation of RawVD

### ISSUE THREAD

**Issue by hcwang95** [proteus1991/RawVSR#3]
Thanks for the interesting paper with great details. 

I am wondering if you have any plan to share the process of dataset generation, which is super beneficial to extends RawVD datasets for other enhancement tasks. For example, it would be great for people to have the parameters tuned for Canon ISP for rawpy to synthesize sRGB from raw.

**Comment by proteus1991** [comment]
Hi,

Since we plan to extend our dataset for other interesting topics, our group decided not to release the data generation codes for now. However, please check it constantly for potential updates.

Xiaohong

**Comment by hcwang95** [comment]
Cool, thanks! Looking forward to other great work extended from this topic!
